name: "Build generator"
description: "Build the generator binary caching build artifacts and dependencies."
inputs:
  debug_mode:
    description: "Enable debug mode for the generator build process."
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - uses: freckle/stack-action@45415a374b7e73c112bc02423a9af7dc2bd43089 # v5
      with:
        working-directory: "./generator/"
        stack-build-arguments: "${{ github.ref_name != 'main' && '--fast' || '' }} --pedantic"
