name: Build and Smoke Test

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    name: ${{ matrix.ghc }}-${{ matrix.deb }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.5', '9.0.1']
        deb: ['stretch', 'buster']
        include:
          - ghc: '8.10.5'
            ghc_minor: '8.10'
          - ghc: '9.0.1'
            ghc_minor: '9.0'
    steps:
      - uses: actions/checkout@v2
      - name: docker build [${{ matrix.ghc }}]
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 8
          max_attempts: 3
          command: |
            docker build --pull \
              -t haskell:${{ matrix.ghc }}-${{ matrix.deb }} \
              ${{ matrix.ghc_minor }}/${{ matrix.deb }}
      - uses: actions/checkout@v2
        with:
          repository: docker-library/official-images
          path: official-images
      - name: run official-images tests
        run: ./official-images/test/run.sh haskell:${{ matrix.ghc }}-${{ matrix.deb }}
