name: "Populate cache for generator"
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0,4' # Make sure to run at least once a week to avoid eviction
jobs:
  populate-cache:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: ./.github/actions/build-generator
