name: "Populate cache for generator"
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0,4' # Make sure to run at least once a week to avoid eviction
jobs:
  populate-cache:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/build-generator
