name: Dockerfile generator
on:
  push:
    paths:
      - '**/*.ncl'
      - 'template/Dockerfile.ncl'
      - 'generate.sh'
      - 'generate_dockerfiles.nu'
      - '.github/workflows/generator.yml'
  pull_request: {}

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Nix
        uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5

      - name: Install dependencies
        run: nix profile add nixpkgs#nickel nixpkgs#nushell

      - name: Generate Dockerfiles
        run: nu ./generate_dockerfiles.nu

      - name: Verify no diff after generation
        run: git diff --exit-code
