name: Dockerfile generator
on:
  push:
    paths:
      - '**/*.ncl'
      - 'template/Dockerfile.ncl'
      - 'generate.sh'
      - 'generate_dockerfiles.nu'
      - '.github/workflows/generator.yml'
  pull_request: {}

jobs:
  generate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Install dependencies
        run: nix profile add nixpkgs#nickel nixpkgs#nushell

      - name: Generate Dockerfiles
        run: nu ./generate_dockerfiles.nu

      - name: Verify no diff after generation
        run: git diff --exit-code
