name: Dockerfile Generator
on:
  push:
    paths:
      - generator
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug mode'
        type: boolean
        default: false
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: ./.github/actions/build-generator
#        with:
#          debug_mode: ${{ github.event.inputs.debug_mode }}
      - name: Run generator
        working-directory: generator
        run: stack exec generator -- --help

      - name: Copy generator binary to artifacts
        working-directory: generator
        run: |
          mkdir -p ../artifacts
          stack --local-bin-path=../artifacts install
      - name: Upload generated artifact to a release
        uses: softprops/action-gh-release@v2.4.1
        with:
          name: Generator
          tag_name: generator-binary
          prerelease: true
          overwrite_files: 'true'
          files: |
            artifacts/generator
