name: Hadolint

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/Dockerfile'
      - '.github/workflows/lint.yml'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hadolint/hadolint-action@v1.6.0
      with:
        recursive: true
