name: Hadolint

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/Dockerfile'
      - '.github/workflows/lint.yml'

jobs:
  hadolint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
      with:
        recursive: true
