name: Validate Windows

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/windows/**/Dockerfile'
      - '.github/workflows/windows.yml'

jobs:
  build-smoke-test:
    timeout-minutes: 30
    runs-on: windows-latest
    name: ${{ matrix.ghc }}-windowsservercore-${{ matrix.os_version }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.0.2']
        os_version: ['ltsc2022']
        include:
          - ghc: '9.0.2'
            ghc_minor: '9.0'
    steps:
      - uses: actions/checkout@v3
      - name: build + smoke test [${{ matrix.ghc }}]
        run: |
          docker build --pull -t haskell:${{ matrix.ghc }}-windowsservercore-${{ matrix.os_version }} ${{ matrix.ghc_minor }}\windows\windowsservercore-${{ matrix.os_version }}
      # - uses: actions/checkout@v2
      #   with:
      #     repository: AlistairB/official-images
      #     ref: haskell-sh
      #     path: official-images
      # - name: run official-images tests
      #   run: ./official-images/test/run.sh haskell:${{ matrix.ghc }}-alpine${{ matrix.os_version }}
